INSERT INTO TIPO_CONTATO
VALUES (1,N'RESIDENCIAL');
INSERT INTO TIPO_CONTATO
VALUES (2,N'CELULAR');
INSERT INTO TIPO_CONTATO
VALUES (3,N'COMERCIAL');
INSERT INTO TIPO_CONTATO
VALUES (4,N'FAX');
INSERT INTO TIPO_CONTATO
VALUES (5,N'RECADO');
INSERT INTO TIPO_CONTATO
VALUES (6,N'OUTROS');