INSERT INTO VEICULO_COMBUSTIVEL
VALUES (1,N'DIESEL');
INSERT INTO VEICULO_COMBUSTIVEL
VALUES (2,N'ETANOL');
INSERT INTO VEICULO_COMBUSTIVEL
VALUES (3,N'GASOLINA');
INSERT INTO VEICULO_COMBUSTIVEL
VALUES (4,N'GNV');
INSERT INTO VEICULO_COMBUSTIVEL
VALUES (5,N'OUTRO');