USE ZX_CC_QA

UPDATE USER_GROUP_ALERT SET EMAIL='zxcc@zirix.com.br';

UPDATE SCHED_WORK SET WORK_STATE_ID=0;
UPDATE SCHED_WORK SET WORK_STATE_ID=1 WHERE WORK_ID IN (1,2,3);
UPDATE SCHED_WORK SET WORK_STATE_ID=2 WHERE WORK_ID = 5;

UPDATE SCHED_WORK SET SCHED_TIMESTAMP=NOW();
UPDATE SCHED_WORK SET END_TIMESTAMP=NULL;
UPDATE SCHED_WORK SET START_TIMESTAMP=NOW() WHERE WORK_ID IN (1,2,3);
UPDATE SCHED_WORK SET START_TIMESTAMP=NOW() WHERE WORK_ID = 5;
UPDATE SCHED_WORK SET END_TIMESTAMP=NOW() WHERE WORK_ID = 5;

UPDATE SCHED_WORK SET RESTRICTION_ID = 1;
UPDATE SCHED_WORK SET RESTRICTION_ID = 2 WHERE WORK_ID IN (1,2,3,4,5);
UPDATE SCHED_WORK SET RESTRICTION_ID = 3 WHERE WORK_ID IN (4,5);
UPDATE SCHED_WORK SET ALERT_STATUS=0;
SELECT WORK_ID,RESTRICTION_ID,SCHED_TIMESTAMP,START_TIMESTAMP,END_TIMESTAMP,WORK_STATE_ID,ALERT_STATUS FROM SCHED_WORK;
